version: '3.6'

networks:
  # network for all services
  tb:
    driver: bridge
services:
  postgres:
    environment:
      POSTGRES_USER: tb
      POSTGRES_PASSWORD: tb
      POSTGRES_DB: tb
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always
